# Generated by Django 5.2.3 on 2025-07-07 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faults", "0002_alter_faultrecord_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faultrecord",
            name="cause",
            field=models.TextField(db_column="故障原因", verbose_name="故障原因"),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="expected_date",
            field=models.DateField(
                blank=True,
                db_column="预计完成日期",
                null=True,
                verbose_name="预计完成日期",
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="fault_type",
            field=models.CharField(
                db_column="故障类型", max_length=50, verbose_name="故障类型"
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="fourth",
            field=models.ForeignKey(
                blank=True,
                db_column="四级分类",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="faults.fourthcategory",
                verbose_name="四级分类",
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="image_count",
            field=models.PositiveIntegerField(
                db_column="图片数量", default=0, verbose_name="图片数量"
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="image_paths",
            field=models.JSONField(
                blank=True, db_column="图片路径", default=list, verbose_name="图片路径"
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="is_valid",
            field=models.BooleanField(
                db_column="是否有效", default=True, verbose_name="是否有效"
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="legacy_date",
            field=models.DateField(
                blank=True,
                db_column="遗留项处理日期",
                null=True,
                verbose_name="遗留项处理日期",
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="location",
            field=models.CharField(
                db_column="位置", max_length=200, verbose_name="位置"
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="location_time",
            field=models.IntegerField(
                blank=True,
                db_column="定位用时(分钟)",
                null=True,
                verbose_name="定位用时(分钟)",
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="materials",
            field=models.CharField(
                blank=True,
                db_column="使用材料",
                max_length=200,
                null=True,
                verbose_name="使用材料",
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="modified_at",
            field=models.DateTimeField(
                auto_now=True, db_column="修改时间", verbose_name="修改时间"
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="modified_by",
            field=models.CharField(
                blank=True,
                db_column="修改人",
                max_length=100,
                null=True,
                verbose_name="修改人",
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="part_name",
            field=models.CharField(
                blank=True,
                db_column="备件名称",
                max_length=100,
                null=True,
                verbose_name="备件名称",
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="part_quantity",
            field=models.IntegerField(
                blank=True, db_column="备件数量", null=True, verbose_name="备件数量"
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="part_replaced",
            field=models.BooleanField(
                db_column="更换备件", default=False, verbose_name="更换备件"
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="phenomenon",
            field=models.TextField(db_column="故障现象", verbose_name="故障现象"),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="progress",
            field=models.TextField(db_column="处理进度", verbose_name="处理进度"),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="receiver",
            field=models.CharField(
                db_column="接收人", max_length=100, verbose_name="接收人"
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="registrar",
            field=models.CharField(
                db_column="登记人", max_length=100, verbose_name="登记人"
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="registration_time",
            field=models.DateTimeField(
                auto_now_add=True, db_column="登记时间", verbose_name="登记时间"
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="replacement_time",
            field=models.IntegerField(
                blank=True,
                db_column="更换用时(分钟)",
                null=True,
                verbose_name="更换用时(分钟)",
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="reporter",
            field=models.CharField(
                db_column="报告人", max_length=100, verbose_name="报告人"
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="secondary",
            field=models.ForeignKey(
                blank=True,
                db_column="二级分类",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="faults.secondarycategory",
                verbose_name="二级分类",
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="solution",
            field=models.TextField(db_column="解决方案", verbose_name="解决方案"),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="source",
            field=models.CharField(
                db_column="故障来源", max_length=100, verbose_name="故障来源"
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("processing", "处理中"),
                    ("resolved", "已解决"),
                ],
                db_column="状态",
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="system",
            field=models.ForeignKey(
                blank=True,
                db_column="系统",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="faults.system",
                verbose_name="系统",
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="technician",
            field=models.CharField(
                db_column="处理人员", max_length=100, verbose_name="处理人员"
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="third",
            field=models.ForeignKey(
                blank=True,
                db_column="三级分类",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="faults.thirdcategory",
                verbose_name="三级分类",
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="time",
            field=models.TimeField(db_column="时间", verbose_name="时间"),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="tools",
            field=models.CharField(
                blank=True,
                db_column="使用工具",
                max_length=200,
                null=True,
                verbose_name="使用工具",
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="train_number",
            field=models.CharField(
                db_column="车号", max_length=10, verbose_name="车号"
            ),
        ),
    ]
