# Generated by Django 5.2.3 on 2025-07-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faults", "0003_alter_faultrecord_cause_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(max_length=20, unique=True, verbose_name="车号"),
                ),
            ],
            options={
                "verbose_name": "车辆",
                "verbose_name_plural": "车辆管理",
            },
        ),
    ]
