# Generated by Django 5.2.3 on 2025-07-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faults", "0004_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="plate_number",
            field=models.CharField(
                db_column="车号", max_length=20, unique=True, verbose_name="车号"
            ),
        ),
    ]
