# Generated by Django 5.2.3 on 2025-07-07 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faults", "0005_alter_vehicle_plate_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faultrecord",
            name="expected_date",
            field=models.DateField(
                blank=True,
                db_column="预计处理日期",
                null=True,
                verbose_name="预计处理日期",
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="location_time",
            field=models.IntegerField(
                blank=True,
                db_column="故障定位用时(分钟)",
                null=True,
                verbose_name="故障定位用时(分钟)",
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="materials",
            field=models.CharField(
                blank=True,
                db_column="辅料",
                max_length=200,
                null=True,
                verbose_name="辅料",
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="part_replaced",
            field=models.BooleanField(
                db_column="是否更换备件", default=False, verbose_name="是否更换备件"
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="progress",
            field=models.TextField(db_column="当前进度", verbose_name="当前进度"),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="receiver",
            field=models.CharField(
                db_column="受理人", max_length=100, verbose_name="受理人"
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="solution",
            field=models.TextField(db_column="处理办法", verbose_name="处理办法"),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="system",
            field=models.ForeignKey(
                blank=True,
                db_column="故障系统",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="faults.system",
                verbose_name="故障系统",
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="technician",
            field=models.CharField(
                db_column="跟进技术人员", max_length=100, verbose_name="跟进技术人员"
            ),
        ),
        migrations.AlterField(
            model_name="faultrecord",
            name="tools",
            field=models.CharField(
                blank=True,
                db_column="工具",
                max_length=200,
                null=True,
                verbose_name="工具",
            ),
        ),
    ]
